### ISSUE TITLE
More Configuration Options

### ISSUE THREAD

**Issue by NotNotPat** [GateGuy/RH-Downloader#2]
Is it possible to set in the config what site to search from? If I know I want to grab RH or SWMC I would like to be able to set that in the config

**Comment by GateGuy** [comment]
Done; though not in this program. I'm not updating RH Downloader anymore, but I released a separate program that includes all the same downloader functionality (and I just added the option to force a specific site so it doesn't ask), plus the ability to automatically apply a folder of downloaded patches to the correct roms so you're not limited to those two sites:
https://github.com/GateGuy/BatchRomPatcher
